#!/bin/bash

if ! command -v fzf &> /dev/null
then
    echo "Install fzf please"
    exit
fi
addr=$(curl -s ifconfig.co)
file=$(ls | fzf -e)

if command -v python3 &> /dev/null; then
    echo "http://$addr:8000/$file"
    python3 -m http.server 8000
elif command -v python &> /dev/null; then
    echo "http://$addr:8000/$file"
    python -m SimpleHTTPServer 8000
else
    echo "Install python3 please"
fi
